# Generated by Django 5.2.6 on 2025-09-21 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=30, unique=True)),
                ('data_version', models.CharField(blank=True, max_length=10, null=True)),
                ('game_creation', models.DateTimeField(blank=True, null=True)),
                ('game_duration', models.IntegerField(blank=True, null=True)),
                ('queue_id', models.IntegerField(blank=True, null=True)),
                ('platform', models.CharField(max_length=10)),
                ('routing', models.CharField(max_length=10)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['platform'], name='core_match_platfor_4a2a08_idx'), models.Index(fields=['routing'], name='core_match_routing_719661_idx')],
            },
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=78, unique=True)),
                ('summoner_id', models.CharField(max_length=63, unique=True)),
                ('account_id', models.CharField(blank=True, max_length=56, null=True)),
                ('name', models.CharField(db_index=True, max_length=30)),
                ('tag_line', models.CharField(blank=True, max_length=5, null=True)),
                ('profile_icon_id', models.IntegerField(blank=True, null=True)),
                ('summoner_level', models.IntegerField(default=0)),
                ('platform', models.CharField(help_text='e.g. na1, euw1', max_length=10)),
                ('routing', models.CharField(help_text='e.g. americas, europe, asia', max_length=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='core_summon_name_4f9e81_idx'), models.Index(fields=['platform'], name='core_summon_platfor_a31551_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=78)),
                ('summoner_name', models.CharField(max_length=30)),
                ('team_id', models.IntegerField()),
                ('champion_id', models.IntegerField(blank=True, null=True)),
                ('champion_name', models.CharField(blank=True, max_length=40, null=True)),
                ('role', models.CharField(blank=True, max_length=20, null=True)),
                ('lane', models.CharField(blank=True, max_length=20, null=True)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('win', models.BooleanField(default=False)),
                ('gold_earned', models.IntegerField(default=0)),
                ('total_minions_killed', models.IntegerField(default=0)),
                ('neutral_minions_killed', models.IntegerField(default=0)),
                ('damage_to_champions', models.IntegerField(default=0)),
                ('item0', models.IntegerField(blank=True, null=True)),
                ('item1', models.IntegerField(blank=True, null=True)),
                ('item2', models.IntegerField(blank=True, null=True)),
                ('item3', models.IntegerField(blank=True, null=True)),
                ('item4', models.IntegerField(blank=True, null=True)),
                ('item5', models.IntegerField(blank=True, null=True)),
                ('item6', models.IntegerField(blank=True, null=True)),
                ('spell1', models.IntegerField(blank=True, null=True)),
                ('spell2', models.IntegerField(blank=True, null=True)),
                ('perk_primary_style', models.IntegerField(blank=True, null=True)),
                ('perk_sub_style', models.IntegerField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.match')),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.summoner')),
            ],
            options={
                'indexes': [models.Index(fields=['puuid'], name='core_matchp_puuid_b6051a_idx'), models.Index(fields=['summoner'], name='core_matchp_summone_ef98ef_idx')],
                'unique_together': {('match', 'puuid')},
            },
        ),
    ]
