# Generated by Django 5.2.6 on 2025-09-21 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_version', models.CharField(blank=True, max_length=10, null=True)),
                ('frame_interval', models.IntegerField(blank=True, help_text='Interval between frames in milliseconds', null=True)),
                ('raw', models.JSONField(blank=True, default=dict, help_text='Raw timeline data from Riot API')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='core.match')),
            ],
            options={
                'indexes': [models.Index(fields=['match'], name='core_matcht_match_i_231366_idx')],
            },
        ),
    ]
