# Generated by Django 5.2.6 on 2025-09-22 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_matchtimeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerYearlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('platform', models.CharField(max_length=10)),
                ('total_matches', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('total_kills', models.IntegerField(default=0)),
                ('total_deaths', models.IntegerField(default=0)),
                ('total_assists', models.IntegerField(default=0)),
                ('total_gold_earned', models.BigIntegerField(default=0)),
                ('total_minions_killed', models.IntegerField(default=0)),
                ('total_neutral_minions_killed', models.IntegerField(default=0)),
                ('total_damage_to_champions', models.BigIntegerField(default=0)),
                ('unique_champions_played', models.IntegerField(default=0)),
                ('most_played_champion', models.CharField(blank=True, max_length=40, null=True)),
                ('most_played_champion_count', models.IntegerField(default=0)),
                ('unique_roles_played', models.IntegerField(default=0)),
                ('unique_lanes_played', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
                ('kda_ratio', models.FloatField(default=0.0)),
                ('average_kills', models.FloatField(default=0.0)),
                ('average_deaths', models.FloatField(default=0.0)),
                ('average_assists', models.FloatField(default=0.0)),
                ('average_gold_per_match', models.FloatField(default=0.0)),
                ('average_cs_per_match', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_stats', to='core.summoner')),
            ],
            options={
                'indexes': [models.Index(fields=['summoner', 'year'], name='core_player_summone_8cbb77_idx'), models.Index(fields=['year', 'platform'], name='core_player_year_07741a_idx'), models.Index(fields=['win_rate'], name='core_player_win_rat_4f665c_idx'), models.Index(fields=['total_matches'], name='core_player_total_m_2c3240_idx')],
                'unique_together': {('summoner', 'year', 'platform')},
            },
        ),
    ]
